# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-17 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Useless',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(max_length=255)),
                ('two', models.CharField(max_length=255)),
                ('three', models.CharField(max_length=255)),
            ],
        ),
    ]
