# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-17 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sup_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell', models.CharField(max_length=255)),
                ('spell_num', models.IntegerField()),
                ('spell_dice', models.IntegerField()),
                ('spell_type', models.CharField(max_length=255)),
            ],
        ),
    ]
